# Generated by Django 4.2.11 on 2025-04-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_awaiting_doctor_approval',
            field=models.BooleanField(default=False),
        ),
    ]
