# Generated by Django 4.2.11 on 2025-04-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_is_awaiting_doctor_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_awaiting_doctor_approval',
        ),
    ]
